title: Future Tom
description: A notebook of experiments
url: "https://futuretom.com"
baseurl: ""

markdown: kramdown
theme: null

collections:
  notes:
    output: true
    permalink: /_notes/:name/

defaults:
  - scope:
      path: ""
    values:
      layout: default

  - scope:
      path: ""
      type: notes
    values:
      layout: note
